<a href="https://colab.research.google.com/github/Alirazakhan18733/DATA-SCIENCE-MASTER/blob/main/Numpy_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### Array Manipulation

In [ ]:
arr=np.random.randint(1,10,(4,4))

In [ ]:
arr

array([[4, 5, 9, 2],
       [6, 3, 3, 3],
       [1, 8, 4, 4],
       [3, 8, 9, 1]])

In [ ]:
arr.reshape(8,2)

array([[4, 5],
       [9, 2],
       [6, 3],
       [3, 3],
       [1, 8],
       [4, 4],
       [3, 8],
       [9, 1]])

In [ ]:
arr

array([[4, 5, 9, 2],
       [6, 3, 3, 3],
       [1, 8, 4, 4],
       [3, 8, 9, 1]])

In [ ]:
arr.T

array([[4, 6, 1, 3],
       [5, 3, 8, 8],
       [9, 3, 4, 9],
       [2, 3, 4, 1]])

In [ ]:
arr.flatten()

array([4, 5, 9, 2, 6, 3, 3, 3, 1, 8, 4, 4, 3, 8, 9, 1])

In [ ]:
arr

array([[4, 5, 9, 2],
       [6, 3, 3, 3],
       [1, 8, 4, 4],
       [3, 8, 9, 1]])

In [ ]:
np.expand_dims(arr,axis=1)

array([[[4, 5, 9, 2]],

       [[6, 3, 3, 3]],

       [[1, 8, 4, 4]],

       [[3, 8, 9, 1]]])

In [ ]:
np.expand_dims(arr,axis=0)


array([[[4, 5, 9, 2],
        [6, 3, 3, 3],
        [1, 8, 4, 4],
        [3, 8, 9, 1]]])

In [ ]:
data=np.array([[1],[2],[3]])

In [ ]:
np.squeeze(data)

array([1, 2, 3])

In [ ]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Binary *Operations*

In [ ]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [ ]:
arr1

array([[4, 9, 4, 8],
       [1, 5, 5, 7],
       [8, 6, 5, 5]])

In [ ]:
arr2

array([[2, 5, 2, 6],
       [1, 7, 8, 1],
       [4, 8, 8, 3]])

In [ ]:
arr1+arr2

array([[ 6, 14,  6, 14],
       [ 2, 12, 13,  8],
       [12, 14, 13,  8]])

In [ ]:
arr1-arr2

array([[ 2,  4,  2,  2],
       [ 0, -2, -3,  6],
       [ 4, -2, -3,  2]])

In [ ]:
arr1*arr2

array([[ 8, 45,  8, 48],
       [ 1, 35, 40,  7],
       [32, 48, 40, 15]])

In [ ]:
arr1/arr2

array([[2.        , 1.8       , 2.        , 1.33333333],
       [1.        , 0.71428571, 0.625     , 7.        ],
       [2.        , 0.75      , 0.625     , 1.66666667]])

In [ ]:
arr1**arr2

array([[     16,   59049,      16,  262144],
       [      1,   78125,  390625,       7],
       [   4096, 1679616,  390625,     125]])

In [ ]:
~arr1

array([[ -5, -10,  -5,  -9],
       [ -2,  -6,  -6,  -8],
       [ -9,  -7,  -6,  -6]])

In [ ]:
arr1

array([[4, 9, 4, 8],
       [1, 5, 5, 7],
       [8, 6, 5, 5]])

In [ ]:
arr1>arr2

array([[ True,  True,  True,  True],
       [False, False, False,  True],
       [ True, False, False,  True]])

### String *Functions*

In [ ]:
arr = np.array(["sudh","kumar"])

In [ ]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [ ]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [ ]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

### Mathmatical Functions

In [ ]:
arr1

array([[4, 9, 4, 8],
       [1, 5, 5, 7],
       [8, 6, 5, 5]])

In [ ]:
np.sin(arr1)

array([[-0.7568025 ,  0.41211849, -0.7568025 ,  0.98935825],
       [ 0.84147098, -0.95892427, -0.95892427,  0.6569866 ],
       [ 0.98935825, -0.2794155 , -0.95892427, -0.95892427]])

In [ ]:
np.cos(arr1)

array([[-0.65364362, -0.91113026, -0.65364362, -0.14550003],
       [ 0.54030231,  0.28366219,  0.28366219,  0.75390225],
       [-0.14550003,  0.96017029,  0.28366219,  0.28366219]])

In [ ]:
np.tan(arr1)

array([[ 1.15782128, -0.45231566,  1.15782128, -6.79971146],
       [ 1.55740772, -3.38051501, -3.38051501,  0.87144798],
       [-6.79971146, -0.29100619, -3.38051501, -3.38051501]])

In [ ]:
np.log10(arr1)

array([[0.60205999, 0.95424251, 0.60205999, 0.90308999],
       [0.        , 0.69897   , 0.69897   , 0.84509804],
       [0.90308999, 0.77815125, 0.69897   , 0.69897   ]])

In [ ]:
np.exp(arr1)

array([[5.45981500e+01, 8.10308393e+03, 5.45981500e+01, 2.98095799e+03],
       [2.71828183e+00, 1.48413159e+02, 1.48413159e+02, 1.09663316e+03],
       [2.98095799e+03, 4.03428793e+02, 1.48413159e+02, 1.48413159e+02]])

In [ ]:
np.power(arr1,2)

array([[16, 81, 16, 64],
       [ 1, 25, 25, 49],
       [64, 36, 25, 25]])

In [ ]:
np.mean(arr1)

5.583333333333333

In [ ]:
np.median(arr1)

5.0

In [ ]:
np.std(arr1)

2.099933861392359

In [ ]:
np.var(arr1)

4.409722222222222

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

9

### Arithmetic Operations

In [ ]:
arr1

array([[4, 9, 4, 8],
       [1, 5, 5, 7],
       [8, 6, 5, 5]])

In [ ]:
arr2

array([[2, 5, 2, 6],
       [1, 7, 8, 1],
       [4, 8, 8, 3]])

In [ ]:
arr1-arr2

array([[ 2,  4,  2,  2],
       [ 0, -2, -3,  6],
       [ 4, -2, -3,  2]])

In [ ]:
np.subtract(arr1,arr2)

array([[ 2,  4,  2,  2],
       [ 0, -2, -3,  6],
       [ 4, -2, -3,  2]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 8, 45,  8, 48],
       [ 1, 35, 40,  7],
       [32, 48, 40, 15]])

In [ ]:
np.mod(arr1,arr2)

array([[0, 4, 0, 2],
       [0, 5, 5, 0],
       [0, 6, 5, 2]])

In [ ]:
np.power(arr1,arr2)

array([[     16,   59049,      16,  262144],
       [      1,   78125,  390625,       7],
       [   4096, 1679616,  390625,     125]])

In [ ]:
np.sqrt(arr1)

array([[2.        , 3.        , 2.        , 2.82842712],
       [1.        , 2.23606798, 2.23606798, 2.64575131],
       [2.82842712, 2.44948974, 2.23606798, 2.23606798]])

### Statistical Functions

In [ ]:
arr1

array([[4, 9, 4, 8],
       [1, 5, 5, 7],
       [8, 6, 5, 5]])

In [ ]:
np.mean(arr1)

5.583333333333333

In [ ]:
np.std(arr1)

2.099933861392359

In [ ]:
np.var(arr1)

4.409722222222222

In [ ]:
np.median(arr1)

5.0