<a href="https://colab.research.google.com/github/Alirazakhan18733/DATA-SCIENCE-MASTER/blob/main/Numpy_Part_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l= [1,2,3,4,5]

In [3]:
arr=np.array(l)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
np.array([[1,2,3,4],[2,4,5,7]])

array([[1, 2, 3, 4],
       [2, 4, 5, 7]])

In [9]:
arr1 = np.array([[1,2,3,4],[2,4,5,7]])

In [12]:
arr.ndim

1

In [13]:
arr1

array([[1, 2, 3, 4],
       [2, 4, 5, 7]])

In [14]:
arr1.ndim

2

In [17]:
mat = np.matrix(l)

In [19]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [20]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
a=arr

In [23]:
a

array([1, 2, 3, 4, 5])

In [24]:
arr[0] = 100

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
a

array([100,   2,   3,   4,   5])

In [27]:
b=  np.copy(arr)

In [28]:
b

array([100,   2,   3,   4,   5])

In [29]:
b[0]=234

In [30]:
b

array([234,   2,   3,   4,   5])

In [31]:
arr

array([100,   2,   3,   4,   5])

In [32]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [39]:
iterable = (i*i for i in range(5))

In [41]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [47]:
np.fromstring('23 45 56' ,sep = ' ')

array([23., 45., 56.])

In [ ]:
np.fromstring('23,45,56',sep = ',')

In [50]:
arr

array([100,   2,   3,   4,   5])

In [51]:
arr1

array([[1, 2, 3, 4],
       [2, 4, 5, 7]])

In [52]:
arr.ndim

1

In [53]:
arr1.ndim

2

In [54]:
arr.size

5

In [55]:
arr1.size


8

In [56]:
arr1.shape

(2, 4)

In [57]:
arr1

array([[1, 2, 3, 4],
       [2, 4, 5, 7]])

In [61]:
arr.dtype

dtype('int64')

In [62]:
arr1.dtype

dtype('int64')